version: 2

sources:
  - name: olist_raw
    database: durable-ripsaw-477914-g0
    schema: ecommerce
    tables:
      - name: olist_orders
      - name: olist_order_items
      - name: olist_order_payments
      - name: olist_order_reviews
      - name: olist_products
      - name: olist_customers
      - name: olist_sellers
      - name: olist_geolocation
      - name: product_category_name_translation


